// ---------------------------------------------------------------------------
// @lathe/contract public surface.
//
// The DTOs + the event union are hand-authored in lathe.contract.ts; `paths`
// is generated by the rivet-ts pipeline (gen:reflect → gen:openapi → gen:client)
// and consumed by the openapi-fetch client in @lathe/cli. Run `pnpm gen` after
// any contract change — generated/ is committed.
// ---------------------------------------------------------------------------

export type * from "./lathe.contract.js";
export type { paths } from "../generated/schema.js";
